#!/usr/bin/env bash

# Code is generated by ucloud-model, DO NOT EDIT IT.

{{ range $index, $test := .GetAll }}
ucloud-model sdk test \
    --lang python3 \
    --template ${U_MODEL_HOME}/providers/python/templates/testing.tpl \
    --output tests/test_services/test_set_{{ $test.ID }}.py \
    --name {{ $test.ID }}
{{ end }}

black tests/test_services/*
